services:
  - type: web
    name: django-whatsapp-text-chat-analysis
    env: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn myproject.wsgi_render:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings_render
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false