"""
Django settings for myproject project.
Generated by 'django-admin startproject' using Django 5.2.4.
<<<<<<< HEAD
=======

This is the general / local settings file. It:
 - uses sqlite by default
 - only includes STATICFILES_DIRS if a local 'static/' folder exists (avoids W004)
 - keeps DEBUG off by default (controlled by env)
>>>>>>> 49340df8744b6570747d6bd4d9b58a8af76954d8
"""

from pathlib import Path
import os
from dotenv import load_dotenv
<<<<<<< HEAD
=======
from urllib.parse import urlparse, unquote
>>>>>>> 49340df8744b6570747d6bd4d9b58a8af76954d8

# Load local .env if present
load_dotenv()

<<<<<<< HEAD
# ---------------- Base settings ----------------
=======
>>>>>>> 49340df8744b6570747d6bd4d9b58a8af76954d8
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-7xtf^8mx%38rgf_xv&*+oqfk1zf746akl@+*vli@w2w_my49az"
)

DEBUG = os.environ.get("DEBUG", "False") == "True"

<<<<<<< HEAD
# ---------------- Hosts & Security ----------------
# Default hosts if env not set
_default_hosts = [
    "127.0.0.1",
    "localhost",
    "whatsapp-text-chat-analysis-system-4q8m.onrender.com",
    "django-whatsapp-text-chat-analysis.onrender.com"
=======
# Hosts - Ensure Render domains are always included
_default_hosts = [
    "127.0.0.1", 
    "localhost", 
    "django-whatsapp-text-chat-analysis.onrender.com",
    "*.onrender.com"  # This will match any Render subdomain
>>>>>>> 49340df8744b6570747d6bd4d9b58a8af76954d8
]
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS")
if ALLOWED_HOSTS:
    ALLOWED_HOSTS = [h.strip() for h in ALLOWED_HOSTS.split(",") if h.strip()]
<<<<<<< HEAD
else:
    ALLOWED_HOSTS = _default_hosts

# CSRF trusted origins (must include scheme https://)
_default_csrf = ["https://whatsapp-text-chat-analysis-system-4q8m.onrender.com", "https://django-whatsapp-text-chat-analysis.onrender.com"]
=======
    # Always add Render domains for safety
    for host in _default_hosts:
        if host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(host)
else:
    ALLOWED_HOSTS = _default_hosts

# CSRF trusted origins (if running with HTTPS locally or on a domain)
>>>>>>> 49340df8744b6570747d6bd4d9b58a8af76954d8
CSRF_TRUSTED_ORIGINS = os.environ.get("CSRF_TRUSTED_ORIGINS")
if CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = [u.strip() for u in CSRF_TRUSTED_ORIGINS.split(",") if u.strip()]
else:
<<<<<<< HEAD
    CSRF_TRUSTED_ORIGINS = _default_csrf

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

# ---------------- Applications ----------------
=======
    CSRF_TRUSTED_ORIGINS = [
        "https://django-whatsapp-text-chat-analysis.onrender.com",
        "https://*.onrender.com"
    ]

# Optional extra keys
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

# Apps
>>>>>>> 49340df8744b6570747d6bd4d9b58a8af76954d8
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "chatapp.apps.ChatappConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
<<<<<<< HEAD
    "whitenoise.middleware.WhiteNoiseMiddleware",
=======
    "whitenoise.middleware.WhiteNoiseMiddleware",  # OK for local & production
>>>>>>> 49340df8744b6570747d6bd4d9b58a8af76954d8
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "myproject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "myproject.wsgi.application"

<<<<<<< HEAD
# ---------------- Database ----------------
=======
# Database (sqlite default)
>>>>>>> 49340df8744b6570747d6bd4d9b58a8af76954d8
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

<<<<<<< HEAD
# ---------------- Password Validators ----------------
=======
# You can set DATABASE_URL env var if you want to use Postgres locally too.
db_url = os.environ.get("DATABASE_URL")
if db_url:
    parsed = urlparse(db_url)
    if parsed.scheme.startswith("postgres"):
        username = unquote(parsed.username) if parsed.username else ""
        password = unquote(parsed.password) if parsed.password else ""
        host = parsed.hostname or ""
        port = parsed.port or ""
        dbname = parsed.path.lstrip("/") if parsed.path else ""
        DATABASES["default"] = {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": dbname,
            "USER": username,
            "PASSWORD": password,
            "HOST": host,
            "PORT": port,
        }

# Password validators
>>>>>>> 49340df8744b6570747d6bd4d9b58a8af76954d8
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

<<<<<<< HEAD
# ---------------- Internationalization ----------------
=======
>>>>>>> 49340df8744b6570747d6bd4d9b58a8af76954d8
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

<<<<<<< HEAD
# ---------------- Static & Media ----------------
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]  # Make sure this folder exists
=======
# Static & media
STATIC_URL = "/static/"
_local_static = BASE_DIR / "static"
if _local_static.exists():
    STATICFILES_DIRS = [_local_static]
else:
    STATICFILES_DIRS = []

>>>>>>> 49340df8744b6570747d6bd4d9b58a8af76954d8
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

<<<<<<< HEAD
# ---------------- Default auto field ----------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ---------------- Upload & Data Limits ----------------
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# ---------------- Cache & Sessions ----------------
=======
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Upload limits
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# Cache & sessions (default local)
>>>>>>> 49340df8744b6570747d6bd4d9b58a8af76954d8
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "memory-cache",
        "TIMEOUT": 300,
        "OPTIONS": {"MAX_ENTRIES": 1000},
    }
}
<<<<<<< HEAD

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
=======
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
>>>>>>> 49340df8744b6570747d6bd4d9b58a8af76954d8
